// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    messagingSenderId: '187030371315', // 312417997266
    projectId: 'authentication-a8e04', // exaustor-2e5f2
    storageBucket: 'authentication-a8e04.appspot.com', // exaustor-2e5f2.appspot.com
    appId: '1:187030371315:android:40031a413207e9cf8d7086', // 1:312417997266:android:6ed21c27402ff48c33f80b
    apiKey: 'AIzaSyC5nu46lpdZ9ediM2DKzb_jg_WYVZgi3W0', // AIzaSyCwVExsnisMVfq2Tsit9IsfeUXKttQ5sXs
    //databaseURL: 'SUA_DATABASE_URL',
    //gcmSenderId: 'SEU_GCM_SENDER_ID',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR5b8yUKodH-J8Kg0UEiUO-8zzlDH4pqE', // AIzaSyB5dbRHYhRnq6veacZOhRJWOh1fzXWhDDs
    messagingSenderId: '187030371315', // 312417997266
    iosBundleId: 'com.example.authentication', // com.sulapps.exaustor
    projectId: 'authentication-a8e04', // exaustor-2e5f2
    storageBucket: 'authentication-a8e04.appspot.com', // exaustor-2e5f2.appspot.com
    appId: '1:187030371315:ios:c96acf5e501f45b08d7086', // 1:312417997266:ios:03a9476a6ac1c74133f80b
    //databaseURL: 'SUA_DATABASE_URL',
    //iosClientId: 'SEU_IOS_CLIENT_ID',
    //androidClientId: 'SEU_ANDROID_CLIENT_ID',
    //deepLinkURLScheme: 'SUA_DEEPLINK_URL_SCHEME',
  );
}
